# Generated by Django 4.2.9 on 2024-02-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.CharField(default='', max_length=150, verbose_name='Автор'),
        ),
    ]
