# Generated by Django 4.2.9 on 2024-02-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_products_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
